name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight
  workflow_dispatch:      # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4   # updated

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: HusHexist
          outputs: dist/snake.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v4   # updated
        with:
          name: snake
          path: dist/snake.svg

      - name: Push Snake to output branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated snake animation"
          add: "dist/snake.svg"
